# -*- coding: utf-8 -*-
"""Calculator

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QUyUiPqR-mprPlxv_Agd8wHFCnDacsXk
"""

# Function to perform addition
def add(x, y):
    return x + y

# Function to perform subtraction
def subtract(x, y):
    return x - y

# Function to perform multiplication
def multiply(x, y):
    return x * y

# Function to perform division
def divide(x, y):
    if y == 0:
        return "Cannot divide by zero"
    return x / y

# Main calculator function
def calculator():
    print("Select operation:")
    print("1. Addition")
    print("2. Subtraction")
    print("3. Multiplication")
    print("4. Division")

    # Take input from the user
    choice = input("Enter choice (1/2/3/4): ")

    # Check if the choice is valid
    if choice not in ('1', '2', '3', '4'):
        print("Invalid input")
        return

    # Input two numbers
    num1 = float(input("Enter first number: "))
    num2 = float(input("Enter second number: "))

    if choice == '1':
        print("Result:", add(num1, num2))
    elif choice == '2':
        print("Result:", subtract(num1, num2))
    elif choice == '3':
        print("Result:", multiply(num1, num2))
    elif choice == '4':
        result = divide(num1, num2)
        if result == "Cannot divide by zero":
            print(result)
        else:
            print("Result:", result)

# Run the calculator
calculator()