# -*- coding: utf-8 -*-
"""GenPassword

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QUyUiPqR-mprPlxv_Agd8wHFCnDacsXk
"""

import random
import string

# Function to generate a random password
def generate_password(length):
    # Define character sets for different complexity levels
    lowercase_letters = string.ascii_lowercase
    uppercase_letters = string.ascii_uppercase
    digits = string.digits
    special_characters = string.punctuation

    # Combine character sets based on complexity level
    if length < 4:
        print("Password length must be at least 4 characters.")
        return ""
    elif length < 8:
        charset = lowercase_letters + digits
    elif length < 12:
        charset = lowercase_letters + uppercase_letters + digits
    else:
        charset = lowercase_letters + uppercase_letters + digits + special_characters

    # Generate the password
    password = ''.join(random.choice(charset) for _ in range(length))
    return password

# Main function
def main():
    try:
        # Prompt the user for password length
        length = int(input("Enter the desired password length: "))

        # Generate and display the password
        password = generate_password(length)
        if password:
            print("Generated Password:", password)
    except ValueError:
        print("Invalid input. Please enter a valid integer for the password length.")

if __name__ == "__main__":
    main()